version: '3.4'
services:
  app:
    restart: always
    networks:
      - some_network
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      POSTGRES_PASSWORD: pgpass
      POSTGRES_USER: pguser
      POSTGRES_DB: pgdb
      POSTGRES_HOST: postgres
    ports:
      - ':8000'
    depends_on:
      - postgres
  postgres:
    container_name: postgres
    networks:
      some_network:
        aliases:
          - postgres
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_PASSWORD=pgpass
      - POSTGRES_USER=pguser
      - POSTGRES_DB=pgdb
    volumes:
      - ./pg_data:/var/lib/postgresql/data
      - ./sql_scripts:/docker-entrypoint-initdb.d
    ports:
      - ':5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U pguser -d pgdb" ]
      interval: 5s
      timeout: 10s
      start_period: 20s
      retries: 5
networks:
  some_network: